CONFIG_PATH = "src/wfi_reference_pipeline/config/"

DARK_SHORT_IDENTIFIER = "00444"
DARK_LONG_IDENTIFIER = "00445"
DARK_SHORT_NUM_READS = 46
DARK_LONG_NUM_READS = 98
DARK_SIGMA_CLIP_SD_LOW = 3
DARK_SIGMA_CLIP_SD_HIGH = 3

DETECTOR_PIXEL_X_COUNT = 4096
DETECTOR_PIXEL_Y_COUNT = 4096
SCI_PIXEL_X_COUNT = 4088
SCI_PIXEL_Y_COUNT = 4088

GB = 1024**3  # 1 GB = 1,073,741,824 bytes
MB = 1024**2  # 1 MB = 1,048,576 bytes

QC_CHECK_FAIL = 0       # "Red", do not deliver
QC_CHECK_SUCCEED = 1    # "Green", all is good to deliver
QC_CHECK_CAUTION = 2    # "Yellow", conditional deliver according to parameters/settings
QC_CHECK_INCOMPLETE = 3 # Not Run

VIRTUAL_PIXEL_DEPTH = 4 # Reference pixels are connected to virtual pixels acting as a 4 element deep border on each slice of an uncalibrated cube

WFI_MODE_WIM = "WIM"
WFI_MODE_WSM = "WSM"

WFI_MODES = {WFI_MODE_WIM, WFI_MODE_WSM}

WFI_DETECTORS_ALL = "ALL"
WFI_DETECTORS = {
    "WFI01",
    "WFI02",
    "WFI03",
    "WFI04",
    "WFI05",
    "WFI06",
    "WFI07",
    "WFI08",
    "WFI09",
    "WFI10",
    "WFI11",
    "WFI12",
    "WFI13",
    "WFI14",
    "WFI15",
    "WFI16",
    "WFI17",
    "WFI18",
}

WFI_FRAME_TIME = {WFI_MODE_WIM: 3.16248, WFI_MODE_WSM: 5.14116}


WFI_P_EXPTYPE_IMAGE = "WFI_IMAGE|"
WFI_P_EXPTYPE_GRISM = "WFI_GRISM|"
WFI_P_EXPTYPE_PRISM = "WFI_PRISM|"


WFI_PEDIGREE = {"GROUND", "MODEL", "DUMMY", "SIMULATION"}


WFI_REF_OPTICAL_ELEMENT_DARK = "DARK"
WFI_REF_OPTICAL_ELEMENT_F062 = "F062"
WFI_REF_OPTICAL_ELEMENT_F087 = "F087"
WFI_REF_OPTICAL_ELEMENT_F106 = "F106"
WFI_REF_OPTICAL_ELEMENT_F129 = "F129"
WFI_REF_OPTICAL_ELEMENT_F146 = "F146"
WFI_REF_OPTICAL_ELEMENT_F158 = "F158"
WFI_REF_OPTICAL_ELEMENT_F184 = "F184"
WFI_REF_OPTICAL_ELEMENT_F213 = "F213"
WFI_REF_OPTICAL_ELEMENT_GRISM = "GRISM"
WFI_REF_OPTICAL_ELEMENT_PRISM = "PRISM"

WFI_REF_OPTICAL_ELEMENTS = {
    WFI_REF_OPTICAL_ELEMENT_DARK,
    WFI_REF_OPTICAL_ELEMENT_F062,
    WFI_REF_OPTICAL_ELEMENT_F087,
    WFI_REF_OPTICAL_ELEMENT_F106,
    WFI_REF_OPTICAL_ELEMENT_F129,
    WFI_REF_OPTICAL_ELEMENT_F146,
    WFI_REF_OPTICAL_ELEMENT_F158,
    WFI_REF_OPTICAL_ELEMENT_F184,
    WFI_REF_OPTICAL_ELEMENT_F213,
    WFI_REF_OPTICAL_ELEMENT_GRISM,
    WFI_REF_OPTICAL_ELEMENT_PRISM,
}

# Ref Type Strings
REF_TYPE_ABVEGAMAGNITUDEOFFSET = "ABVEGAOFFSET"
REF_TYPE_APERTURECORRECTION = "APCORR"
REF_TYPE_DARK = "DARK"
REF_TYPE_DARKDECAYSIGNAL = "DARKDECAYSIGNAL"
REF_TYPE_DETECTORSTATUS = "DETECTORSTATUS"
REF_TYPE_DISTORTION = "DISTORTION"
REF_TYPE_ETC = "ETC"
REF_TYPE_FLAT = "FLAT"
REF_TYPE_GAIN = "GAIN"
REF_TYPE_INTEGRALNONLINEARITY = "INTEGRALNONLINEARITY"
REF_TYPE_INVERSELINEARITY = "INVERSELINEARITY"
REF_TYPE_IPC = "IPC"
REF_TYPE_LINEARITY = "LINEARITY"
REF_TYPE_MASK = "MASK"
REF_TYPE_MULTIACCUMULATIONTABLE = "MATABLE"
REF_TYPE_PHOTOM = "PHOTOM"
REF_TYPE_PIXELAREA = "PIXELAREA"
REF_TYPE_READNOISE = "READNOISE"
REF_TYPE_REF_COMMON = "REF_COMMON"
REF_TYPE_REF_EXPOSURE_TYPE = "REF_EXPOSURE_TYPE"
REF_TYPE_REF_OPTICAL_ELEMENT = "REF_OPTICAL_ELEMENT"
REF_TYPE_REFPIX = "REFPIX"
REF_TYPE_SATURATION = "SATURATION"
REF_TYPE_SUPERBIAS = "SUPERBIAS"


WFI_REF_TYPES = {
    REF_TYPE_ABVEGAMAGNITUDEOFFSET,
    REF_TYPE_APERTURECORRECTION,
    REF_TYPE_DARK,
    REF_TYPE_DARKDECAYSIGNAL,
    REF_TYPE_DETECTORSTATUS,
    REF_TYPE_DISTORTION,
    REF_TYPE_ETC,
    REF_TYPE_FLAT,
    REF_TYPE_GAIN,
    REF_TYPE_INTEGRALNONLINEARITY,
    REF_TYPE_INVERSELINEARITY,
    REF_TYPE_IPC,
    REF_TYPE_LINEARITY,
    REF_TYPE_MASK,
    REF_TYPE_MULTIACCUMULATIONTABLE,
    REF_TYPE_PHOTOM,
    REF_TYPE_PIXELAREA,
    REF_TYPE_READNOISE,
    REF_TYPE_REF_COMMON,
    REF_TYPE_REF_EXPOSURE_TYPE,
    REF_TYPE_REF_OPTICAL_ELEMENT,
    REF_TYPE_REFPIX,
    REF_TYPE_SATURATION,
    REF_TYPE_SUPERBIAS
}

WFI_REF_TYPES_WITHOUT_INPUT_DATA = {
    REF_TYPE_ABVEGAMAGNITUDEOFFSET,
    REF_TYPE_APERTURECORRECTION,
    REF_TYPE_DARKDECAYSIGNAL,
    REF_TYPE_DETECTORSTATUS,
    REF_TYPE_ETC,
    REF_TYPE_PHOTOM,
    REF_TYPE_PIXELAREA,
}

WFI_TYPE_IMAGE = "WFI_IMAGE"
WFI_TYPE_GRISM = "WFI_GRISM"
WFI_TYPE_PRISM = "WFI_PRISM"

WFI_TYPES = {WFI_TYPE_IMAGE, WFI_TYPE_GRISM, WFI_TYPE_PRISM}
